version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toefl
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"

  api:
    build: ./backend
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
volumes:
  pgdata:

